### ISSUE TITLE
Can't access question button

### ISSUE THREAD

**Issue by pacosta613** [learn-co-curriculum/oo-cash-register#16]
Dont know if its the server im one but I cant seem to access the "ask" button.

**Comment by AnnJohn** [comment]
Hi @pacosta613 is this still an issue? And if there are issues like this with the Learn interface, could you file a bug report? If you hover over your profile pic in Learn, you'll see an option to Report a Bug. Thanks.

**Comment by pacosta613** [comment]
The issue isn't present anymore.

**Comment by AnnJohn** [comment]
Great.
