### ISSUE TITLE
Suggestion: Integer vs. Float

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/oo-cash-register#23]
I recently helped a student who was getting unexpected results in their `#apply_discount` method, and the core of the issue rested in the difference between an `Integer` and a `Float` in Ruby.

I don't believe this is mentioned explicitly in the previous lessons, and I think that some students may not even be aware that a `Float` class exists. Therefore, I feel that a hint or note in this lesson would be helpful.

If there is a consensus that this would indeed be helpful, I'd be happy to create a PR.

@aturkewi

**Comment by JeffKatzy** [comment]
Added hint.
